;;;; test-android.lisp — Android tooling tests: AXML, APK, v1 JAR signing.
;;;;
;;;; CC0 1.0 Universal — public domain. See LICENSE.

(in-package #:clef-test)

;;; --- shared helpers ---

(defun t-bv (string)
  "ASCII STRING as a byte vector."
  (map '(simple-array (unsigned-byte 8) (*)) #'char-code string))

(defun t-hex (bytes)
  (with-output-to-string (s)
    (loop for b across bytes do (format s "~(~2,'0x~)" b))))

(defun t-u16 (bytes pos) (logior (aref bytes pos) (ash (aref bytes (1+ pos)) 8)))

(defun t-u32 (bytes pos)
  (logior (aref bytes pos) (ash (aref bytes (1+ pos)) 8)
          (ash (aref bytes (+ pos 2)) 16) (ash (aref bytes (+ pos 3)) 24)))

;;; --- test RSA key + self-signed certificate ---
;;; Generated by tools/dev/gen-test-key.lisp (a 1024-bit throwaway test key
;;; with a deterministic random state; NOT for production use). The script
;;; uses only clef/android's own DER writer and RSA signer.

(defparameter *test-key-der*
  (coerce '(48 130 2 94 2 1 0 2 129 129 0 155 53 218 210 109 12 42 139 255 187
            147 142 141 16 240 65 135 77 128 196 116 94 244 241 214 214 86 5
            134 209 220 212 116 218 83 197 155 158 173 60 167 114 120 170 78 16
            98 17 228 93 223 19 147 78 217 109 233 46 7 80 36 136 156 95 19 121
            45 32 207 215 149 128 250 148 89 167 38 29 125 9 6 65 215 22 117 78
            99 180 225 63 13 72 246 131 59 243 61 1 236 129 191 43 30 139 95
            210 4 28 207 157 206 90 118 48 24 158 215 114 113 25 179 231 226
            209 100 145 32 79 2 3 1 0 1 2 129 128 71 167 10 25 32 204 128 11
            215 136 145 235 58 70 122 147 213 209 186 195 118 241 171 100 198 8
            118 247 224 48 156 32 220 189 57 245 61 13 120 238 74 99 55 63 112
            0 114 53 206 86 99 184 150 197 204 236 199 188 63 22 9 119 163 176
            43 141 242 145 91 148 200 85 234 64 97 92 178 159 134 164 228 198
            199 52 34 157 72 88 68 125 140 217 162 210 149 65 188 19 180 204 28
            74 42 66 87 164 223 201 134 199 179 39 198 198 20 162 181 23 134 22
            183 233 74 198 135 133 6 201 2 65 0 178 84 16 225 217 53 47 106 89
            152 137 57 232 73 13 220 237 228 56 149 55 156 230 39 62 87 167 3 3
            119 76 218 208 116 248 111 76 193 197 74 65 24 163 10 85 27 84 164
            215 57 62 230 253 15 192 106 65 236 15 132 207 74 195 109 2 65 0
            222 208 22 203 81 238 139 49 185 204 104 124 112 55 51 186 47 33 50
            70 146 51 206 19 107 206 3 43 238 238 185 121 6 111 63 23 172 226
            208 231 36 102 96 167 120 130 199 212 99 34 132 46 253 246 186 192
            154 224 170 186 107 14 97 43 2 65 0 167 139 128 73 17 144 124 186 8
            239 221 142 64 133 210 182 141 243 236 141 149 176 158 52 164 200
            41 172 21 39 147 87 202 158 251 131 102 180 111 174 114 54 185 136
            77 169 221 254 250 15 88 224 33 71 25 91 60 16 148 12 13 206 138
            137 2 65 0 147 27 38 1 133 13 142 126 253 33 148 214 155 172 6 141
            229 49 240 164 161 64 108 205 107 190 175 95 97 55 225 226 162 185
            238 24 238 127 45 215 125 179 206 26 163 185 12 192 15 215 169 23
            241 122 229 159 230 97 112 182 245 153 159 211 2 65 0 142 178 174
            172 92 228 255 205 165 190 148 101 200 163 72 178 146 155 110 85
            246 133 140 77 238 151 153 85 20 50 163 120 170 23 24 243 4 223 252
            113 200 176 186 89 123 85 232 127 101 122 140 90 184 28 111 171 216
            0 182 187 33 13 212 209) '(simple-array (unsigned-byte 8) (*))))

(defparameter *test-cert-der*
  (coerce '(48 130 1 156 48 130 1 5 160 3 2 1 2 2 1 1 48 13 6 9 42 6 200 6 247
            141 1 1 11 5 0 48 20 49 18 48 16 6 3 85 4 3 12 9 67 76 69 70 32 84
            101 115 116 48 30 23 13 50 53 48 49 48 49 48 48 48 48 48 48 90 23
            13 52 53 48 49 48 49 48 48 48 48 48 48 90 48 20 49 18 48 16 6 3 85
            4 3 12 9 67 76 69 70 32 84 101 115 116 48 129 159 48 13 6 9 42 6
            200 6 247 141 1 1 1 5 0 3 129 141 0 48 129 137 2 129 129 0 155 53
            218 210 109 12 42 139 255 187 147 142 141 16 240 65 135 77 128 196
            116 94 244 241 214 214 86 5 134 209 220 212 116 218 83 197 155 158
            173 60 167 114 120 170 78 16 98 17 228 93 223 19 147 78 217 109 233
            46 7 80 36 136 156 95 19 121 45 32 207 215 149 128 250 148 89 167
            38 29 125 9 6 65 215 22 117 78 99 180 225 63 13 72 246 131 59 243
            61 1 236 129 191 43 30 139 95 210 4 28 207 157 206 90 118 48 24 158
            215 114 113 25 179 231 226 209 100 145 32 79 2 3 1 0 1 48 13 6 9 42
            6 200 6 247 141 1 1 11 5 0 3 129 129 0 146 243 86 73 46 166 200 136
            187 226 124 111 185 207 221 165 174 1 162 236 180 199 58 166 27 84
            20 104 12 29 75 234 93 153 84 81 175 104 116 87 227 33 166 200 196
            56 43 104 51 215 147 156 79 89 71 84 14 244 120 43 38 254 202 250
            122 136 147 153 1 37 93 116 192 189 143 75 210 234 115 151 192 10
            232 177 18 20 192 190 127 223 209 40 103 169 99 128 173 24 72 142
            136 64 138 74 103 23 22 116 182 27 18 248 102 56 109 216 86 116 167
            58 37 151 55 169 192 224 78 191) '(simple-array (unsigned-byte 8) (*))))

(defparameter *test-key-n* 108992428509001712745373675962640590129460186367310837960865805211665563794398617874423853929395513631895404442460707909154491277510111902693874013932897297312582842420873873540480345391166010579174842207959513752839456791329675084668816321775463645008423611511162146882591801464882044435193206388957952155727)
(defparameter *test-key-e* 65537)
(defparameter *test-key-d* 50316095099559742116839046130425424635958587340631847696812410343453951700558923719283667251077425956833475157646042964912478959993109779452876364367301022240118551056326967389693876754984128946772459398142655881867976222111811002753449310578315761945356717995677789987684840098104110541924617654612374390473)

;;; --- SHA-256 (FIPS 180-4 known-answer vectors) ---

(deftest android-sha256-vectors
  (is (string= (t-hex (clef/android:sha256 (make-array 0 :element-type '(unsigned-byte 8))))
               "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"))
  (is (string= (t-hex (clef/android:sha256 (t-bv "abc")))
               "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"))
  (is (string= (t-hex (clef/android:sha256
                       (t-bv "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")))
               "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1")))

;;; --- base64 (RFC 4648 test vectors) ---

(deftest android-base64-vectors
  (dolist (pair '(("" . "") ("f" . "Zg==") ("fo" . "Zm8=") ("foo" . "Zm9v")
                  ("foob" . "Zm9vYg==") ("fooba" . "Zm9vYmE=")
                  ("foobar" . "Zm9vYmFy")))
    (is (string= (clef/android:base64-encode (t-bv (car pair))) (cdr pair))
        (format nil "base64 of ~s" (car pair)))))

;;; --- ZIP round trip ---

(deftest android-zip-roundtrip
  (let* ((e1 (clef/android:make-entry "a.txt" (t-bv "hello")))
         (e2 (clef/android:make-entry "dir/b.bin"
                                      (make-array 3 :element-type '(unsigned-byte 8)
                                                  :initial-contents '(0 1 255))))
         (zip (clef/android:write-zip (list e1 e2)))
         (entries (clef/android:read-zip zip)))
    (is (= (length entries) 2))
    (is (equal (mapcar #'clef/android:zentry-name entries)
               '("a.txt" "dir/b.bin")))
    (is (equalp (clef/android:zentry-data (first entries)) (t-bv "hello")))
    (is (equalp (clef/android:zentry-data (second entries))
                (clef/android:zentry-data e2)))
    ;; EOCD magic at the tail.
    (is (= (t-u32 zip (- (length zip) 22)) #x06054b50))))

;;; --- AXML: re-parse what we emit ---

(defun axml-parse (bytes)
  "Parse the AXML byte vector BYTES. Returns (values strings events resmap)
where EVENTS is a list of (:start-ns prefix uri), (:end-ns prefix uri),
(:start name attrs) or (:end name), and attrs is a list of
(name-string type-keyword value) with values resolved (string/int/bool)."
  (is (= (t-u16 bytes 0) #x0003) "AXML file type must be RES_XML_TYPE")
  (is (= (t-u16 bytes 2) 8) "AXML header size must be 8")
  (is (= (t-u32 bytes 4) (length bytes)) "AXML size field must cover the file")
  (let ((pos 8)
        (strings '())
        (resmap '())
        (events '()))
    (labels ((len-field (p)
               "Read a UTF-8 string-pool length field at P; return (values n next)."
               (let ((b (aref bytes p)))
                 (if (< b #x80)
                     (values b (1+ p))
                     (values (logior (ash (logand b #x7F) 8) (aref bytes (1+ p)))
                             (+ p 2)))))
             (parse-pool (p)
               (let ((count (t-u32 bytes (+ p 8)))
                     (flags (t-u32 bytes (+ p 16)))
                     (strings-start (t-u32 bytes (+ p 20))))
                 (is (= (logand flags #x100) #x100) "pool must be UTF-8")
                 (dotimes (i count)
                   (let ((sp (+ p strings-start (t-u32 bytes (+ p 28 (* 4 i))))))
                     (multiple-value-bind (u16len q) (len-field sp)
                       (declare (ignore u16len))
                       (multiple-value-bind (u8len r) (len-field q)
                         (push (map 'string #'code-char
                                    (subseq bytes r (+ r u8len)))
                               strings)))))))
             (attr-value (p raw type data)
               (case type
                 (#x03 (values (nth (- (length strings) 1 data) strings) :string))
                 (#x10 (values data :int))
                 (#x12 (values (not (zerop data)) :bool))
                 (t (values raw :unknown))))
             (parse-start-el (p)
               (let* ((name-idx (t-u32 bytes (+ p 20)))
                      (attr-start (t-u16 bytes (+ p 24)))
                      (attr-count (t-u16 bytes (+ p 28)))
                      (attrs '()))
                 (dotimes (i attr-count)
                   (let ((ap (+ p 16 attr-start (* i 20))))
                     (let ((aname (nth (- (length strings) 1 (t-u32 bytes (+ ap 4)))
                                       strings))
                           (raw (t-u32 bytes (+ ap 8)))
                           (type (aref bytes (+ ap 15)))
                           (data (t-u32 bytes (+ ap 16))))
                       (multiple-value-bind (value kind) (attr-value ap raw type data)
                         (declare (ignore raw))
                         (push (list aname kind value) attrs)))))
                 (push (list :start (nth (- (length strings) 1 name-idx) strings)
                             (nreverse attrs))
                       events))))
      (loop while (< pos (length bytes))
            for type = (t-u16 bytes pos)
            for size = (t-u32 bytes (+ pos 4))
            do (case type
                 (#x0001 (parse-pool pos))
                 (#x0180 (dotimes (i (/ (- size 8) 4))
                           (push (t-u32 bytes (+ pos 8 (* 4 i))) resmap)))
                 (#x0100 (push (list :start-ns
                                     (nth (- (length strings) 1 (t-u32 bytes (+ pos 16))) strings)
                                     (nth (- (length strings) 1 (t-u32 bytes (+ pos 20))) strings))
                               events))
                 (#x0101 (push (list :end-ns
                                     (nth (- (length strings) 1 (t-u32 bytes (+ pos 16))) strings)
                                     (nth (- (length strings) 1 (t-u32 bytes (+ pos 20))) strings))
                               events))
                 (#x0102 (parse-start-el pos))
                 (#x0103 (push (list :end (nth (- (length strings) 1 (t-u32 bytes (+ pos 20)))
                                               strings))
                               events))
                 (t (error "Unexpected chunk type ~x at ~d" type pos)))
               (incf pos size)))
    (values (nreverse strings) (nreverse events) (nreverse resmap))))

(defun t-manifest ()
  (clef/android:write-android-manifest
   :package "com.example.clef" :version-name "0.1" :version-code 7
   :min-sdk 26 :target-sdk 34 :main-activity ".MainActivity"))

(deftest android-axml-magic
  (let ((m (t-manifest)))
    ;; 0x00080003 little-endian: the AXML magic.
    (is (= (t-u32 m 0) #x00080003))
    (is (= (t-u32 m 4) (length m)))
    ;; The string-pool chunk follows the 8-byte file header.
    (is (= (t-u16 m 8) #x0001))))

(deftest android-axml-string-pool
  (multiple-value-bind (strings events resmap) (axml-parse (t-manifest))
    (declare (ignore events))
    (dolist (expected '("com.example.clef" ".MainActivity"
                        "android.intent.action.MAIN"
                        "android.intent.category.LAUNCHER"
                        "manifest" "uses-sdk" "application" "activity"
                        "intent-filter" "action" "category"
                        "package" "versionCode" "versionName"
                        "minSdkVersion" "targetSdkVersion" "name" "exported"
                        "android" "http://schemas.android.com/apk/res/android"
                        "0.1"))
      (is (member expected strings :test #'string=)
          (format nil "string pool must contain ~s" expected)))
    ;; The resource map covers the first eight pool entries (the mappable
    ;; attribute names), in resource-ID order.
    (is (equal resmap '(#x01010003 #x01010006 #x01010010 #x01010024
                        #x0101020c #x0101021b #x0101021c #x01010270)))
    (is (equal (subseq strings 0 8)
               '("name" "hasCode" "exported" "value" "minSdkVersion"
                 "versionCode" "versionName" "targetSdkVersion")))))

(deftest android-axml-element-roundtrip
  (multiple-value-bind (strings events resmap) (axml-parse (t-manifest))
    (declare (ignore strings resmap))
    (flet ((attr (event name)
             (find name (third event) :key #'first :test #'string=)))
      ;; Namespace events bracket the document element.
      (is (equal (first events)
                 (list :start-ns "android" "http://schemas.android.com/apk/res/android")))
      (is (equal (car (last events))
                 (list :end-ns "android" "http://schemas.android.com/apk/res/android")))
      ;; Element sequence, ignoring the namespace events.
      (let ((elements (remove-if (lambda (e) (member (first e) '(:start-ns :end-ns)))
                                 events)))
        (is (equal (mapcar (lambda (e) (list (first e) (second e))) elements)
                   '((:start "manifest")
                     (:start "uses-sdk") (:end "uses-sdk")
                     (:start "application")
                     (:start "activity")
                     (:start "intent-filter")
                     (:start "action") (:end "action")
                     (:start "category") (:end "category")
                     (:end "intent-filter")
                     (:end "activity")
                     (:end "application")
                     (:end "manifest"))))
        (let ((manifest (find "manifest" elements :key #'second :test #'string=))
              (uses-sdk (find "uses-sdk" elements :key #'second :test #'string=))
              (activity (find "activity" elements :key #'second :test #'string=))
              (action (find "action" elements :key #'second :test #'string=))
              (category (find "category" elements :key #'second :test #'string=)))
          (is (equal (attr manifest "package") '("package" :string "com.example.clef")))
          (is (equal (attr manifest "versionCode") '("versionCode" :int 7)))
          (is (equal (attr manifest "versionName") '("versionName" :string "0.1")))
          (is (equal (attr uses-sdk "minSdkVersion") '("minSdkVersion" :int 26)))
          (is (equal (attr uses-sdk "targetSdkVersion") '("targetSdkVersion" :int 34)))
          (is (equal (attr activity "name") '("name" :string ".MainActivity")))
          (is (equal (attr activity "exported") '("exported" :bool t)))
          (is (equal (attr action "name")
                     '("name" :string "android.intent.action.MAIN")))
          (is (equal (attr category "name")
                     '("name" :string "android.intent.category.LAUNCHER"))))))))

;;; --- AXML: NativeActivity (hasCode="false") manifest mode ---

(defun t-native-manifest ()
  (clef/android:write-android-manifest
   :package "org.clef.repl" :version-name "0.1" :version-code 1
   :min-sdk 30 :target-sdk 34
   :has-code nil :lib-name "clef" :exported t))

(deftest android-axml-native-activity
  (multiple-value-bind (strings events resmap) (axml-parse (t-native-manifest))
    ;; The pool carries the NativeActivity class, the lib_name meta-data
    ;; key, and the library name itself.
    (dolist (expected '("android.app.NativeActivity" "android.app.lib_name"
                        "clef" "hasCode" "value" "meta-data" "application"
                        "activity" "org.clef.repl"))
      (is (member expected strings :test #'string=)
          (format nil "string pool must contain ~s" expected)))
    ;; hasCode and value joined the resource map, IDs still sorted.
    (is (equal resmap '(#x01010003 #x01010006 #x01010010 #x01010024
                        #x0101020c #x0101021b #x0101021c #x01010270)))
    (let ((elements (remove-if (lambda (e) (member (first e) '(:start-ns :end-ns)))
                               events)))
      (flet ((attr (event name)
               (find name (third event) :key #'first :test #'string=)))
        (let ((application (find "application" elements :key #'second :test #'string=))
              (activity (find "activity" elements :key #'second :test #'string=))
              (meta-data (find "meta-data" elements :key #'second :test #'string=)))
          ;; android:hasCode="false" as a boolean typed value on <application>.
          (is (equal (attr application "hasCode") '("hasCode" :bool nil)))
          ;; The fixed NativeActivity class, boolean-true android:exported.
          (is (equal (attr activity "name")
                     '("name" :string "android.app.NativeActivity")))
          (is (equal (attr activity "exported") '("exported" :bool t)))
          ;; meta-data android.app.lib_name = "clef".
          (is (equal (attr meta-data "name")
                     '("name" :string "android.app.lib_name")))
          (is (equal (attr meta-data "value") '("value" :string "clef"))))))))

(deftest android-axml-native-activity-default-mode-unchanged
  ;; Default mode (has-code t): still .MainActivity, no hasCode attribute,
  ;; no meta-data element.
  (multiple-value-bind (strings events) (axml-parse (t-manifest))
    (let* ((elements (remove-if (lambda (e) (member (first e) '(:start-ns :end-ns)))
                                events))
           (application (find "application" elements :key #'second :test #'string=))
           (activity (find "activity" elements :key #'second :test #'string=)))
      (is (member ".MainActivity" strings :test #'string=))
      (is (equal (find "name" (third activity) :key #'first :test #'string=)
                 '("name" :string ".MainActivity")))
      (is (not (find "hasCode" (third application) :key #'first :test #'string=))
          "default mode must not emit android:hasCode")
      (is (not (find "meta-data" elements :key #'second :test #'string=))
          "default mode must not emit a meta-data element"))))

(deftest android-axml-native-activity-requires-lib-name
  (signals-error (clef/android:write-android-manifest
                  :package "org.clef.repl" :version-name "0.1" :version-code 1
                  :min-sdk 30 :target-sdk 34 :has-code nil))
  (signals-error (clef/android:write-android-manifest
                  :package "org.clef.repl" :version-name "0.1" :version-code 1
                  :min-sdk 30 :target-sdk 34 :has-code nil :lib-name "")))

;;; --- UI DSL (JNI call plans) ---

(defun t-plan ()
  (clef/android:jni-plan
   (clef/android:layout
    (clef/android:text-view :title :text "hi")
    (clef/android:button :ok :text "OK" :on-tap 'foo))))

(defun t-plan-find (plan &key op class name)
  (find-if (lambda (d) (and (or (null op) (eq (getf d :op) op))
                            (or (null class) (equal (getf d :class) class))
                            (or (null name) (equal (getf d :name) name))))
           plan))

(deftest android-ui-jni-plan
  (let ((plan (t-plan)))
    ;; First op instantiates the root LinearLayout.
    (let ((first-op (first plan)))
      (is (eq (getf first-op :op) :new-object))
      (is (equal (getf first-op :class) "android/widget/LinearLayout"))
      (is (eq (getf first-op :id) :root)))
    ;; The root is configured vertical: setOrientation(1).
    (is (equal (t-plan-find plan :name "setOrientation")
               '(:op :call-method :id :root :class "android/widget/LinearLayout"
                 :name "setOrientation" :signature "(I)V" :args (1))))
    ;; A TextView is instantiated and gets setText("hi") with the real
    ;; CharSequence signature.
    (is (t-plan-find plan :op :new-object :class "android/widget/TextView"))
    (is (equal (t-plan-find plan :class "android/widget/TextView" :name "setText")
               '(:op :call-method :id :title :class "android/widget/TextView"
                 :name "setText" :signature "(Ljava/lang/CharSequence;)V"
                 :args ("hi"))))
    ;; A Button is instantiated and its click listener references the
    ;; on-tap symbol as data.
    (is (t-plan-find plan :op :new-object :class "android/widget/Button"))
    (let ((listener (t-plan-find plan :name "setOnClickListener")))
      (is listener)
      (is (eq (getf listener :id) :ok))
      (is (equal (getf listener :class) "android/widget/Button"))
      (is (equal (getf listener :signature)
                 "(Landroid/view/View$OnClickListener;)V"))
      (is (equal (getf listener :args) '((:callback foo)))))
    ;; The children are attached to the root.
    (is (member '(:op :add-view :parent :root :child :title) plan :test #'equal))
    (is (member '(:op :add-view :parent :root :child :ok) plan :test #'equal))
    ;; Every id referenced by an :add-view op was defined by an earlier
    ;; :new-object op (parent-first ordering).
    (let ((defined '()))
      (dolist (d plan)
        (case (getf d :op)
          (:new-object (push (getf d :id) defined))
          (:add-view
           (is (member (getf d :parent) defined)
               "add-view parent must be instantiated earlier in the plan")
           (is (member (getf d :child) defined)
               "add-view child must be instantiated earlier in the plan")))))))

(deftest android-ui-text-input-hint
  (let ((plan (clef/android:jni-plan
               (clef/android:layout
                (clef/android:text-input :entry :hint "type here")))))
    ;; A text-input lowers to android/widget/EditText ...
    (is (t-plan-find plan :op :new-object :class "android/widget/EditText"))
    ;; ... with setHint when :hint is given.
    (is (equal (t-plan-find plan :name "setHint")
               '(:op :call-method :id :entry :class "android/widget/EditText"
                 :name "setHint" :signature "(Ljava/lang/CharSequence;)V"
                 :args ("type here"))))
    ;; No setText when :text was not given.
    (is (not (t-plan-find plan :name "setText")))))

;;; --- APK packager ---

(defun t-unsigned-apk ()
  (clef/android:build-apk
   :package "com.example.clef" :version-name "0.1" :version-code 7
   :min-sdk 26 :target-sdk 34 :main-activity ".MainActivity"
   :so-files (list (cons "lib/arm64-v8a/libclef.so" (t-bv "fake-elf-bytes")))
   :assets (list (cons "assets/boot.lisp" (t-bv "abc")))))

(deftest android-apk-entries
  (let* ((entries (clef/android:read-zip (t-unsigned-apk)))
         (names (mapcar #'clef/android:zentry-name entries)))
    (is (equal names '("AndroidManifest.xml"
                       "lib/arm64-v8a/libclef.so"
                       "assets/boot.lisp")))
    (let ((manifest (find "AndroidManifest.xml" entries
                          :key #'clef/android:zentry-name :test #'string=)))
      ;; The manifest entry must start with the AXML magic 0x00080003 (LE).
      (is (= (t-u32 (clef/android:zentry-data manifest) 0) #x00080003)))
    (is (equalp (clef/android:zentry-data
                 (find "lib/arm64-v8a/libclef.so" entries
                       :key #'clef/android:zentry-name :test #'string=))
                (t-bv "fake-elf-bytes")))))

;;; --- v1 JAR signing ---

(defun t-signed-apk ()
  (clef/android:sign-apk (t-unsigned-apk)
                         :private-key *test-key-der*
                         :certificate *test-cert-der*))

(defun t-entry (entries name)
  (find name entries :key #'clef/android:zentry-name :test #'string=))

(defun t-public-key ()
  (clef/android:make-rsa-public-key :n *test-key-n* :e *test-key-e*))

(deftest android-sign-adds-meta-inf
  (let* ((entries (clef/android:read-zip (t-signed-apk)))
         (names (mapcar #'clef/android:zentry-name entries)))
    (is (equal names '("META-INF/MANIFEST.MF" "META-INF/CLEF.SF" "META-INF/CLEF.RSA"
                       "AndroidManifest.xml" "lib/arm64-v8a/libclef.so"
                       "assets/boot.lisp")))))

(deftest android-sign-manifest-digests
  (let* ((entries (clef/android:read-zip (t-signed-apk)))
         (mf (map 'string #'code-char
                  (clef/android:zentry-data (t-entry entries "META-INF/MANIFEST.MF")))))
    (is (search "Manifest-Version: 1.0" mf))
    ;; Independently known value: base64 of the FIPS-known SHA-256 of "abc"
    ;; (ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad).
    (is (search (concatenate 'string "Name: assets/boot.lisp" (string #\Return)
                             (string #\Newline)
                             "SHA-256-Digest: ungWv48Bz+pBQUDeXa4iI7ADYaOWF3qctBD/YfIAFa0=")
                mf)
        "MANIFEST.MF must carry the known SHA-256 digest of the \"abc\" asset")
    ;; Every non-META-INF entry gets a Name section with a digest that
    ;; matches a freshly computed SHA-256/base64 of its bytes.
    (dolist (entry entries)
      (unless (clef/android::signing-file-p (clef/android:zentry-name entry))
        (let ((expected (concatenate 'string
                                     "Name: " (clef/android:zentry-name entry) (string #\Return)
                                     (string #\Newline)
                                     "SHA-256-Digest: "
                                     (clef/android:base64-encode
                                      (clef/android:sha256
                                       (clef/android:zentry-data entry))))))
          (is (search expected mf)
              (format nil "digest section for ~a"
                      (clef/android:zentry-name entry))))))))

(deftest android-sign-sf-digest
  (let* ((entries (clef/android:read-zip (t-signed-apk)))
         (mf-bytes (clef/android:zentry-data (t-entry entries "META-INF/MANIFEST.MF")))
         (sf (map 'string #'code-char
                  (clef/android:zentry-data (t-entry entries "META-INF/CLEF.SF")))))
    (is (search "Signature-Version: 1.0" sf))
    (is (search (concatenate 'string "SHA-256-Digest-Manifest: "
                             (clef/android:base64-encode (clef/android:sha256 mf-bytes)))
                sf)
        "CLEF.SF must digest the whole MANIFEST.MF")))

(defun t-pkcs7-signature (rsa-bytes)
  "Walk the PKCS#7 SignedData DER and return (values signature-octets
content-info-oid-tag-signed-ok cert-embedded)."
  (let* ((top (clef/android:der-parse rsa-bytes))
         (top-children (clef/android:der-node-children top)))
    (is (= (clef/android:der-node-tag top) #x30) "PKCS#7 top must be a SEQUENCE")
    (is (= (length top-children) 2) "ContentInfo: OID + [0] content")
    ;; [0] EXPLICIT SignedData
    (let* ((content (second top-children))
           (signed-data (first (clef/android:der-node-children content)))
           (fields (clef/android:der-node-children signed-data)))
      (is (= (clef/android:der-node-tag content) #xA0))
      (is (= (length fields) 5)
          "SignedData: version, digestAlgorithms, contentInfo, certs, signerInfos")
      ;; certificates [0] holds the raw cert; compare with the fixture.
      (let ((certs (nth 3 fields)))
        (is (= (clef/android:der-node-tag certs) #xA0))
        (is (equalp (clef/android:der-node-content certs) *test-cert-der*)
            "CLEF.RSA must embed the signer's certificate"))
      ;; signerInfos: SET OF one SignerInfo; signature is its last field.
      (let* ((signer-info (first (clef/android:der-node-children (nth 4 fields))))
             (si-fields (clef/android:der-node-children signer-info)))
        (is (= (length si-fields) 5)
            "SignerInfo without authenticated attributes has 5 fields")
        (is (= (clef/android:der-node-tag (nth 4 si-fields)) #x04)
            "encryptedDigest must be an OCTET STRING")
        (values (clef/android:der-node-content (nth 4 si-fields)))))))

(deftest android-sign-rsa-verifies
  (let* ((entries (clef/android:read-zip (t-signed-apk)))
         (sf-bytes (clef/android:zentry-data (t-entry entries "META-INF/CLEF.SF")))
         (rsa-bytes (clef/android:zentry-data (t-entry entries "META-INF/CLEF.RSA")))
         (signature (t-pkcs7-signature rsa-bytes)))
    ;; The signature must be one modulus-sized block that verifies against
    ;; the public key over the CLEF.SF bytes.
    (is (= (length signature) 128) "1024-bit RSA signature")
    (is (clef/android:rsa-verify-sha256 (t-public-key) sf-bytes signature))
    ;; Check the EMSA-PKCS1-v1_5 structure of the decrypted signature:
    ;; 00 01 FF..FF 00 DigestInfo(SHA-256) || H(CLEF.SF).
    (let* ((m (clef/android::mod-expt (clef/android:der-integer-value signature)
                                      *test-key-e* *test-key-n*))
           (em (make-array 128 :element-type '(unsigned-byte 8))))
      (dotimes (i 128)
        (setf (aref em (- 127 i)) (logand (ash m (* -8 i)) #xFF)))
      (is (and (= (aref em 0) 0) (= (aref em 1) 1)))
      ;; PS occupies indices 2 .. 2+PS-1 where PS = 128-3-51; the 00
      ;; separator and the 51-byte DigestInfo follow.
      (is (loop for i from 2 below (+ 2 (- 128 3 51)) always (= (aref em i) #xFF)))
      (is (= (aref em (+ 2 (- 128 3 51))) 0))
      (is (equalp (subseq em (- 128 51) (- 128 32))
                  clef/android::+sha256-digestinfo-prefix+))
      (is (equalp (subseq em (- 128 32)) (clef/android:sha256 sf-bytes))))))

(deftest android-sign-tamper-fails
  (let* ((entries (clef/android:read-zip (t-signed-apk)))
         (sf-bytes (clef/android:zentry-data (t-entry entries "META-INF/CLEF.SF")))
         (rsa-bytes (clef/android:zentry-data (t-entry entries "META-INF/CLEF.RSA")))
         (signature (t-pkcs7-signature rsa-bytes))
         (tampered (copy-seq sf-bytes)))
    (setf (aref tampered 10) (logxor (aref tampered 10) 1))
    (is (not (clef/android:rsa-verify-sha256 (t-public-key) tampered signature)))))

(deftest android-sign-requires-key
  (signals-error (clef/android:sign-apk (t-unsigned-apk)))
  (signals-error (clef/android:sign-apk (t-unsigned-apk)
                                        :private-key *test-key-der*)))
