;;;; builtins.lisp — host-backed builtins for CLEF-H.
;;;;
;;;; CC0 1.0 Universal — public domain. See LICENSE.
;;;;
;;;; Installs the core function namespace into a toplevel environment. Host
;;;; functions are wrapped to route through clef-apply where they must call
;;;; back into Lisp (funcall, apply, mapcar, etc.). This is the bootstrap
;;;; layer; the boot library (boot.lisp) defines the rest in Lisp itself.

(in-package #:clef/proto/eval)

(defun install-builtins (env)
  "Install core builtins into ENV (a toplevel environment). Returns ENV."
  (let ((reg (lambda (name fn)
               (clef/proto/env:set-function-value env name fn)))
        (regh (lambda (name host-fn)
                ;; register a host CL function directly
                (clef/proto/env:set-function-value env name host-fn))))

    ;;; --- function application (must call back into Lisp) ---
    (funcall reg 'cl:funcall
             (lambda (fn &rest args) (clef-apply fn args)))
    (funcall reg 'cl:apply
             (lambda (fn &rest args)
               (clef-apply fn (apply #'list* args))))
    (funcall reg 'cl:functionp (lambda (x) (or (clef-function-p x) (functionp x))))
    (funcall reg 'cl:fboundp (lambda (n) (clef/proto/env:function-bound-p env n)))

    ;;; --- evaluation / environment ---
    (funcall reg 'cl:eval (lambda (form) (primary (clef-eval form env))))
    (funcall reg 'cl:macroexpand-1
             (lambda (form) (clef-macroexpand-1 form env)))
    (funcall reg 'cl:macroexpand
             (lambda (form) (values (clef-macroexpand form env))))
    (funcall reg 'cl:values (lambda (&rest vals) (values-list vals)))
    (funcall reg 'cl:values-list (lambda (list) (values-list list)))
    (funcall reg 'cl:nth-value (lambda (n mv) (nth n mv)))

    ;;; --- conses ---
    (funcall regh 'cl:cons #'cons)
    (funcall regh 'cl:car #'car)
    (funcall regh 'cl:cdr #'cdr)
    (funcall regh 'cl:caar #'caar)
    (funcall regh 'cl:cadr #'cadr)
    (funcall regh 'cl:cdar #'cdar)
    (funcall regh 'cl:cddr #'cddr)
    (funcall regh 'cl:caaar #'caaar)
    (funcall regh 'cl:caadr #'caadr)
    (funcall regh 'cl:cadar #'cadar)
    (funcall regh 'cl:caddr #'caddr)
    (funcall regh 'cl:cdaar #'cdaar)
    (funcall regh 'cl:cdadr #'cdadr)
    (funcall regh 'cl:cddar #'cddar)
    (funcall regh 'cl:cdddr #'cdddr)
    (funcall regh 'cl:caaaar #'caaaar)
    (funcall regh 'cl:caaadr #'caaadr)
    (funcall regh 'cl:caadar #'caadar)
    (funcall regh 'cl:caaddr #'caaddr)
    (funcall regh 'cl:cadaar #'cadaar)
    (funcall regh 'cl:cadadr #'cadadr)
    (funcall regh 'cl:caddar #'caddar)
    (funcall regh 'cl:cadddr #'cadddr)
    (funcall regh 'cl:cdaaar #'cdaaar)
    (funcall regh 'cl:cdaadr #'cdaadr)
    (funcall regh 'cl:cdadar #'cdadar)
    (funcall regh 'cl:cdaddr #'cdaddr)
    (funcall regh 'cl:cddaar #'cddaar)
    (funcall regh 'cl:cddadr #'cddadr)
    (funcall regh 'cl:cdddar #'cdddar)
    (funcall regh 'cl:cddddr #'cddddr)
    (funcall regh 'cl:rplaca #'rplaca)
    (funcall regh 'cl:rplacd #'rplacd)
    (funcall regh 'cl:consp #'consp)
    (funcall regh 'cl:atom #'atom)
    (funcall regh 'cl:listp #'listp)
    (funcall regh 'cl:null #'null)
    (funcall regh 'cl:endp #'endp)
    (funcall regh 'cl:list #'list)
    (funcall regh 'cl:list* #'list*)
    (funcall regh 'cl:list-length #'list-length)
    (funcall regh 'cl:length #'length)
    (funcall regh 'cl:reverse #'reverse)
    (funcall regh 'cl:nreverse #'nreverse)
    (funcall regh 'cl:append #'append)
    (funcall regh 'cl:nconc #'nconc)
    (funcall regh 'cl:last #'last)
    (funcall regh 'cl:butlast #'butlast)
    (funcall regh 'cl:nbutlast #'nbutlast)
    (funcall regh 'cl:ldiff #'ldiff)
    (funcall regh 'cl:tailp #'tailp)
    (funcall regh 'cl:nth #'nth)
    (funcall regh 'cl:nthcdr #'nthcdr)
    (funcall regh 'cl:member #'member)
    (funcall regh 'cl:member-if #'member-if)
    (funcall regh 'cl:member-if-not #'member-if-not)
    (funcall regh 'cl:adjoin #'adjoin)
    (funcall regh 'cl:assoc #'assoc)
    (funcall regh 'cl:rassoc #'rassoc)
    (funcall regh 'cl:subst #'subst)
    (funcall regh 'cl:nsubst #'nsubst)
    (funcall regh 'cl:subst-if #'subst-if)
    (funcall regh 'cl:sublis #'sublis)
    (funcall regh 'cl:nsublis #'nsublis)
    (funcall regh 'cl:copy-list #'copy-list)
    (funcall regh 'cl:copy-tree #'copy-tree)
    (funcall regh 'cl:copy-alist #'copy-alist)
    (funcall regh 'cl:tree-equal #'tree-equal)
    (funcall regh 'cl:getf #'getf)
    (funcall regh 'cl:get-properties #'get-properties)
    (funcall regh 'cl:acons #'acons)
    (funcall regh 'cl:pairlis #'pairlis)
    (funcall regh 'cl:make-list #'make-list)
    (funcall regh 'cl:mapc #'mapc)
    (funcall reg 'cl:mapcar
             (lambda (fn &rest lists) (apply #'mapcar (coerce-map-fn fn) lists)))
    (funcall reg 'cl:mapcan
             (lambda (fn &rest lists) (apply #'mapcan (coerce-map-fn fn) lists)))
    (funcall reg 'cl:mapl
             (lambda (fn &rest lists) (apply #'mapl (coerce-map-fn fn) lists)))
    (funcall reg 'cl:maplist
             (lambda (fn &rest lists) (apply #'maplist (coerce-map-fn fn) lists)))

    ;;; --- predicates / equality ---
    (funcall regh 'cl:eq #'eq)
    (funcall regh 'cl:eql #'eql)
    (funcall regh 'cl:equal #'equal)
    (funcall regh 'cl:equalp #'equalp)
    (funcall regh 'cl:not #'not)
    (funcall regh 'cl:type-of #'type-of)
    (funcall regh 'cl:typep #'typep)
    (funcall regh 'cl:identity #'identity)
    (funcall regh 'cl:constantly #'constantly)
    (funcall regh 'cl:complement #'complement)

    ;;; --- symbols ---
    (funcall regh 'cl:symbolp #'symbolp)
    (funcall regh 'cl:keywordp #'keywordp)
    (funcall regh 'cl:symbol-name #'symbol-name)
    (funcall regh 'cl:symbol-package #'symbol-package)
    (funcall regh 'cl:symbol-plist #'symbol-plist)
    (funcall regh 'cl:boundp #'boundp)
    (funcall regh 'cl:makunbound #'makunbound)
    (funcall regh 'cl:fmakunbound #'fmakunbound)
    (funcall regh 'cl:gensym #'gensym)
    (funcall regh 'cl:gentemp #'gentemp)
    (funcall regh 'cl:intern #'intern)
    (funcall regh 'cl:find-symbol #'find-symbol)
    (funcall regh 'cl:make-symbol #'make-symbol)
    (funcall regh 'cl:symbol-value #'symbol-value)
    (funcall regh 'cl:set #'set)
    (funcall reg 'cl:symbol-function
             (lambda (n) (clef/proto/env:lookup-function env n)))

    ;;; --- numbers ---
    (funcall regh 'cl:+ #'+)
    (funcall regh 'cl:- #'-)
    (funcall regh 'cl:* #'*)
    (funcall regh 'cl:/ #'/)
    (funcall regh 'cl:1+ #'1+)
    (funcall regh 'cl:1- #'1-)
    (funcall regh 'cl:= #'=)
    (funcall regh 'cl:/= #'/=)
    (funcall regh 'cl:< #'<)
    (funcall regh 'cl:> #'>)
    (funcall regh 'cl:<= #'<=)
    (funcall regh 'cl:>= #'>=)
    (funcall regh 'cl:max #'max)
    (funcall regh 'cl:min #'min)
    (funcall regh 'cl:abs #'abs)
    (funcall regh 'cl:signum #'signum)
    (funcall regh 'cl:numberp #'numberp)
    (funcall regh 'cl:integerp #'integerp)
    (funcall regh 'cl:rationalp #'rationalp)
    (funcall regh 'cl:floatp #'floatp)
    (funcall regh 'cl:realp #'realp)
    (funcall regh 'cl:complexp #'complexp)
    (funcall regh 'cl:zerop #'zerop)
    (funcall regh 'cl:plusp #'plusp)
    (funcall regh 'cl:minusp #'minusp)
    (funcall regh 'cl:evenp #'evenp)
    (funcall regh 'cl:oddp #'oddp)
    (funcall regh 'cl:mod #'mod)
    (funcall regh 'cl:rem #'rem)
    (funcall regh 'cl:floor #'floor)
    (funcall regh 'cl:ceiling #'ceiling)
    (funcall regh 'cl:truncate #'truncate)
    (funcall regh 'cl:round #'round)
    (funcall regh 'cl:ffloor #'ffloor)
    (funcall regh 'cl:fceiling #'fceiling)
    (funcall regh 'cl:ftruncate #'ftruncate)
    (funcall regh 'cl:fround #'fround)
    (funcall regh 'cl:expt #'expt)
    (funcall regh 'cl:sqrt #'sqrt)
    (funcall regh 'cl:isqrt #'isqrt)
    (funcall regh 'cl:exp #'exp)
    (funcall regh 'cl:log #'log)
    (funcall regh 'cl:sin #'sin)
    (funcall regh 'cl:cos #'cos)
    (funcall regh 'cl:tan #'tan)
    (funcall regh 'cl:asin #'asin)
    (funcall regh 'cl:acos #'acos)
    (funcall regh 'cl:atan #'atan)
    (funcall regh 'cl:sinh #'sinh)
    (funcall regh 'cl:cosh #'cosh)
    (funcall regh 'cl:tanh #'tanh)
    (funcall regh 'cl:asinh #'asinh)
    (funcall regh 'cl:acosh #'acosh)
    (funcall regh 'cl:atanh #'atanh)
    (clef/proto/env:defconstant* env 'cl:pi cl:pi)
    (funcall regh 'cl:random #'random)
    (funcall regh 'cl:gcd #'gcd)
    (funcall regh 'cl:lcm #'lcm)
    (funcall regh 'cl:numerator #'numerator)
    (funcall regh 'cl:denominator #'denominator)
    (funcall regh 'cl:rational #'rational)
    (funcall regh 'cl:rationalize #'rationalize)
    (funcall regh 'cl:float #'float)
    (funcall regh 'cl:complex #'complex)
    (funcall regh 'cl:realpart #'realpart)
    (funcall regh 'cl:imagpart #'imagpart)
    (funcall regh 'cl:conjugate #'conjugate)
    (funcall regh 'cl:phase #'phase)
    (funcall regh 'cl:cis #'cis)
    (funcall regh 'cl:logand #'logand)
    (funcall regh 'cl:logior #'logior)
    (funcall regh 'cl:logxor #'logxor)
    (funcall regh 'cl:lognot #'lognot)
    (funcall regh 'cl:lognand #'lognand)
    (funcall regh 'cl:lognor #'lognor)
    (funcall regh 'cl:logandc1 #'logandc1)
    (funcall regh 'cl:logandc2 #'logandc2)
    (funcall regh 'cl:logorc1 #'logorc1)
    (funcall regh 'cl:logorc2 #'logorc2)
    (funcall regh 'cl:logeqv #'logeqv)
    (funcall regh 'cl:logtest #'logtest)
    (funcall regh 'cl:logbitp #'logbitp)
    (funcall regh 'cl:logcount #'logcount)
    (funcall regh 'cl:ash #'ash)
    (funcall regh 'cl:integer-length #'integer-length)
    (funcall regh 'cl:boole #'boole)
    (funcall regh 'cl:ldb #'ldb)
    (funcall regh 'cl:dpb #'dpb)
    (funcall regh 'cl:ldb-test #'ldb-test)
    (funcall regh 'cl:mask-field #'mask-field)
    (funcall regh 'cl:deposit-field #'deposit-field)
    (funcall regh 'cl:byte #'byte)
    (funcall regh 'cl:byte-size #'byte-size)
    (funcall regh 'cl:byte-position #'byte-position)

    ;;; --- sequences ---
    (funcall regh 'cl:elt #'elt)
    (funcall regh 'cl:subseq #'subseq)
    (funcall regh 'cl:copy-seq #'copy-seq)
    (funcall regh 'cl:fill #'fill)
    (funcall regh 'cl:replace #'replace)
    (funcall regh 'cl:count #'count)
    (funcall regh 'cl:count-if #'count-if)
    (funcall regh 'cl:count-if-not #'count-if-not)
    (funcall regh 'cl:find #'find)
    (funcall regh 'cl:find-if #'find-if)
    (funcall regh 'cl:find-if-not #'find-if-not)
    (funcall regh 'cl:position #'position)
    (funcall regh 'cl:position-if #'position-if)
    (funcall regh 'cl:position-if-not #'position-if-not)
    (funcall regh 'cl:remove #'remove)
    (funcall regh 'cl:remove-if #'remove-if)
    (funcall regh 'cl:remove-if-not #'remove-if-not)
    (funcall regh 'cl:delete #'delete)
    (funcall regh 'cl:delete-if #'delete-if)
    (funcall regh 'cl:delete-if-not #'delete-if-not)
    (funcall regh 'cl:remove-duplicates #'remove-duplicates)
    (funcall regh 'cl:delete-duplicates #'delete-duplicates)
    (funcall regh 'cl:substitute #'substitute)
    (funcall regh 'cl:nsubstitute #'nsubstitute)
    (funcall regh 'cl:mismatch #'mismatch)
    (funcall regh 'cl:search #'search)
    (funcall regh 'cl:sort (lambda (seq pred &rest keys)
                             (apply #'sort seq (coerce-map-fn pred) keys)))
    (funcall regh 'cl:stable-sort (lambda (seq pred &rest keys)
                                    (apply #'stable-sort seq (coerce-map-fn pred) keys)))
    (funcall regh 'cl:merge (lambda (type s1 s2 pred &rest keys)
                              (apply #'merge type s1 s2 (coerce-map-fn pred) keys)))
    (funcall regh 'cl:concatenate #'concatenate)
    (funcall regh 'cl:map (lambda (type fn &rest seqs)
                            (apply #'map type (coerce-map-fn fn) seqs)))
    (funcall reg 'cl:map-into
             (lambda (result fn &rest seqs)
               (apply #'map-into result (coerce-map-fn fn) seqs)))
    (funcall reg 'cl:reduce
             (lambda (fn seq &rest keys) (apply #'reduce (coerce-map-fn fn) seq keys)))
    (funcall reg 'cl:every
             (lambda (fn &rest seqs) (apply #'every (coerce-map-fn fn) seqs)))
    (funcall reg 'cl:some
             (lambda (fn &rest seqs) (apply #'some (coerce-map-fn fn) seqs)))
    (funcall reg 'cl:notevery
             (lambda (fn &rest seqs) (apply #'notevery (coerce-map-fn fn) seqs)))
    (funcall reg 'cl:notany
             (lambda (fn &rest seqs) (apply #'notany (coerce-map-fn fn) seqs)))

    ;;; --- vectors / arrays ---
    (funcall regh 'cl:vector #'vector)
    (funcall regh 'cl:vectorp #'vectorp)
    (funcall regh 'cl:simple-vector-p #'simple-vector-p)
    (funcall regh 'cl:svref #'svref)
    (funcall regh 'cl:aref #'aref)
    (funcall regh 'cl:make-array #'make-array)
    (funcall regh 'cl:arrayp #'arrayp)
    (funcall regh 'cl:array-dimension #'array-dimension)
    (funcall regh 'cl:array-dimensions #'array-dimensions)
    (funcall regh 'cl:array-rank #'array-rank)
    (funcall regh 'cl:array-total-size #'array-total-size)
    (funcall regh 'cl:array-element-type #'array-element-type)
    (funcall regh 'cl:adjust-array #'adjust-array)
    (funcall regh 'cl:row-major-aref #'row-major-aref)
    (funcall regh 'cl:array-row-major-index #'array-row-major-index)
    (funcall regh 'cl:vector-push #'vector-push)
    (funcall regh 'cl:vector-push-extend #'vector-push-extend)
    (funcall regh 'cl:fill-pointer #'fill-pointer)
    (funcall regh 'cl:array-has-fill-pointer-p #'array-has-fill-pointer-p)
    (funcall regh 'cl:bit #'bit)
    (funcall regh 'cl:sbit #'sbit)

    ;;; --- strings / characters ---
    (funcall regh 'cl:string #'string)
    (funcall regh 'cl:stringp #'stringp)
    (funcall regh 'cl:simple-string-p #'simple-string-p)
    (funcall regh 'cl:char #'char)
    (funcall regh 'cl:schar #'schar)
    (funcall regh 'cl:make-string #'make-string)
    (funcall regh 'cl:string= #'string=)
    (funcall regh 'cl:string/= #'string/=)
    (funcall regh 'cl:string< #'string<)
    (funcall regh 'cl:string> #'string>)
    (funcall regh 'cl:string<= #'string<=)
    (funcall regh 'cl:string>= #'string>=)
    (funcall regh 'cl:string-equal #'string-equal)
    (funcall regh 'cl:string-not-equal #'string-not-equal)
    (funcall regh 'cl:string-lessp #'string-lessp)
    (funcall regh 'cl:string-greaterp #'string-greaterp)
    (funcall regh 'cl:string-not-lessp #'string-not-lessp)
    (funcall regh 'cl:string-not-greaterp #'string-not-greaterp)
    (funcall regh 'cl:string-upcase #'string-upcase)
    (funcall regh 'cl:string-downcase #'string-downcase)
    (funcall regh 'cl:string-capitalize #'string-capitalize)
    (funcall regh 'cl:nstring-upcase #'nstring-upcase)
    (funcall regh 'cl:nstring-downcase #'nstring-downcase)
    (funcall regh 'cl:string-trim #'string-trim)
    (funcall regh 'cl:string-left-trim #'string-left-trim)
    (funcall regh 'cl:string-right-trim #'string-right-trim)
    (funcall regh 'cl:char-code #'char-code)
    (funcall regh 'cl:code-char #'code-char)
    (funcall regh 'cl:character #'character)
    (funcall regh 'cl:characterp #'characterp)
    (funcall regh 'cl:char= #'char=)
    (funcall regh 'cl:char/= #'char/=)
    (funcall regh 'cl:char< #'char<)
    (funcall regh 'cl:char> #'char>)
    (funcall regh 'cl:char<= #'char<=)
    (funcall regh 'cl:char>= #'char>=)
    (funcall regh 'cl:char-equal #'char-equal)
    (funcall regh 'cl:char-not-equal #'char-not-equal)
    (funcall regh 'cl:char-lessp #'char-lessp)
    (funcall regh 'cl:char-greaterp #'char-greaterp)
    (funcall regh 'cl:char-upcase #'char-upcase)
    (funcall regh 'cl:char-downcase #'char-downcase)
    (funcall regh 'cl:char-name #'char-name)
    (funcall regh 'cl:name-char #'name-char)
    (funcall regh 'cl:alpha-char-p #'alpha-char-p)
    (funcall regh 'cl:alphanumericp #'alphanumericp)
    (funcall regh 'cl:digit-char #'digit-char)
    (funcall regh 'cl:digit-char-p #'digit-char-p)
    (funcall regh 'cl:graphic-char-p #'graphic-char-p)
    (funcall regh 'cl:standard-char-p #'standard-char-p)
    (funcall regh 'cl:upper-case-p #'upper-case-p)
    (funcall regh 'cl:lower-case-p #'lower-case-p)
    (funcall regh 'cl:both-case-p #'both-case-p)
    (funcall regh 'cl:char-int #'char-int)
    (funcall regh 'cl:parse-integer #'parse-integer)
    (funcall regh 'cl:parse-namestring #'parse-namestring)

    ;;; --- hash tables ---
    (funcall regh 'cl:make-hash-table #'make-hash-table)
    (funcall regh 'cl:hash-table-p #'hash-table-p)
    (funcall regh 'cl:gethash #'gethash)
    (funcall regh 'cl:remhash #'remhash)
    (funcall regh 'cl:clrhash #'clrhash)
    (funcall regh 'cl:hash-table-count #'hash-table-count)
    (funcall regh 'cl:hash-table-size #'hash-table-size)
    (funcall regh 'cl:hash-table-test #'hash-table-test)
    (funcall regh 'cl:hash-table-rehash-size #'hash-table-rehash-size)
    (funcall regh 'cl:hash-table-rehash-threshold #'hash-table-rehash-threshold)
    (funcall regh 'cl:sxhash #'sxhash)
    (funcall reg 'cl:maphash
             (lambda (fn table)
               (maphash (lambda (k v) (clef-apply fn (list k v))) table)))
    (funcall regh 'cl:with-hash-table-iterator
      (lambda (fn table) (with-hash-table-iterator (it table) (funcall fn it))))

    ;;; --- packages ---
    (funcall regh 'cl:find-package #'find-package)
    (funcall regh 'cl:make-package #'make-package)
    (funcall regh 'cl:packagep #'packagep)
    (funcall regh 'cl:package-name #'package-name)
    (funcall regh 'cl:package-nicknames #'package-nicknames)
    (funcall regh 'cl:package-use-list #'package-use-list)
    (funcall regh 'cl:package-used-by-list #'package-used-by-list)
    (funcall regh 'cl:package-shadowing-symbols #'package-shadowing-symbols)
    (funcall regh 'cl:list-all-packages #'list-all-packages)
    (funcall regh 'cl:use-package #'use-package)
    (funcall regh 'cl:unuse-package #'unuse-package)
    (funcall regh 'cl:export #'export)
    (funcall regh 'cl:unexport #'unexport)
    (funcall regh 'cl:import #'import)
    (funcall regh 'cl:shadow #'shadow)
    (funcall regh 'cl:shadowing-import #'shadowing-import)
    (funcall regh 'cl:delete-package #'delete-package)
    (funcall regh 'cl:rename-package #'rename-package)
    ;; in-package is a host concern for the prototype; make it a setq of *package*.
    (funcall reg 'cl:in-package
             (lambda (pkg) (setf *package* (find-package pkg)) pkg))

    ;;; --- I/O ---
    (funcall regh 'cl:format #'format)
    (funcall regh 'cl:print #'print)
    (funcall regh 'cl:prin1 #'prin1)
    (funcall regh 'cl:princ #'princ)
    (funcall regh 'cl:pprint #'pprint)
    (funcall regh 'cl:terpri #'terpri)
    (funcall regh 'cl:fresh-line #'fresh-line)
    (funcall regh 'cl:write #'write)
    (funcall regh 'cl:write-to-string #'write-to-string)
    (funcall regh 'cl:prin1-to-string #'prin1-to-string)
    (funcall regh 'cl:princ-to-string #'princ-to-string)
    (funcall regh 'cl:write-char #'write-char)
    (funcall regh 'cl:write-string #'write-string)
    (funcall regh 'cl:write-line #'write-line)
    (funcall regh 'cl:write-byte #'write-byte)
    (funcall regh 'cl:read #'read)
    (funcall regh 'cl:read-char #'read-char)
    (funcall regh 'cl:peek-char #'peek-char)
    (funcall regh 'cl:unread-char #'unread-char)
    (funcall regh 'cl:read-line #'read-line)
    (funcall regh 'cl:read-from-string #'read-from-string)
    (funcall regh 'cl:read-preserving-whitespace #'read-preserving-whitespace)
    (funcall regh 'cl:read-delimited-list #'read-delimited-list)
    (funcall regh 'cl:read-byte #'read-byte)
    (funcall regh 'cl:y-or-n-p #'y-or-n-p)
    (funcall regh 'cl:yes-or-no-p #'yes-or-no-p)
    (funcall regh 'cl:open #'open)
    (funcall regh 'cl:close #'close)
    (funcall regh 'cl:streamp #'streamp)
    (funcall regh 'cl:input-stream-p #'input-stream-p)
    (funcall regh 'cl:output-stream-p #'output-stream-p)
    (funcall regh 'cl:interactive-stream-p #'interactive-stream-p)
    (funcall regh 'cl:stream-element-type #'stream-element-type)
    (funcall regh 'cl:make-string-input-stream #'make-string-input-stream)
    (funcall regh 'cl:make-string-output-stream #'make-string-output-stream)
    (funcall regh 'cl:get-output-stream-string #'get-output-stream-string)
    (funcall regh 'cl:make-concatenated-stream #'make-concatenated-stream)
    (funcall regh 'cl:make-echo-stream #'make-echo-stream)
    (funcall regh 'cl:make-broadcast-stream #'make-broadcast-stream)
    (funcall regh 'cl:make-two-way-stream #'make-two-way-stream)
    (funcall regh 'cl:make-synonym-stream #'make-synonym-stream)
    (funcall regh 'cl:file-position #'file-position)
    (funcall regh 'cl:file-length #'file-length)
    (funcall regh 'cl:file-namestring #'file-namestring)
    (funcall regh 'cl:probe-file #'probe-file)
    (funcall regh 'cl:rename-file #'rename-file)
    (funcall regh 'cl:delete-file #'delete-file)
    (funcall regh 'cl:ensure-directories-exist #'ensure-directories-exist)
    (funcall regh 'cl:truename #'truename)
    (funcall regh 'cl:user-homedir-pathname #'user-homedir-pathname)
    (funcall regh 'cl:pathname #'pathname)
    (funcall regh 'cl:pathnamep #'pathnamep)
    (funcall regh 'cl:merge-pathnames #'merge-pathnames)
    (funcall regh 'cl:namestring #'namestring)
    (funcall regh 'cl:directory-namestring #'directory-namestring)
    (funcall regh 'cl:enough-namestring #'enough-namestring)
    (funcall regh 'cl:host-namestring #'host-namestring)
    (funcall regh 'cl:pathname-host #'pathname-host)
    (funcall regh 'cl:pathname-device #'pathname-device)
    (funcall regh 'cl:pathname-directory #'pathname-directory)
    (funcall regh 'cl:pathname-name #'pathname-name)
    (funcall regh 'cl:pathname-type #'pathname-type)
    (funcall regh 'cl:pathname-version #'pathname-version)
    (funcall regh 'cl:make-pathname #'make-pathname)
    (funcall regh 'cl:directory #'directory)
    (funcall regh 'cl:load #'load)

    ;;; --- printer control vars as toplevel specials ---
    (clef/proto/env:defparameter* env 'cl:*print-readably* *print-readably*)
    (clef/proto/env:defparameter* env 'cl:*print-escape* *print-escape*)
    (clef/proto/env:defparameter* env 'cl:*print-level* *print-level*)
    (clef/proto/env:defparameter* env 'cl:*print-length* *print-length*)
    (clef/proto/env:defparameter* env 'cl:*print-circle* *print-circle*)
    (clef/proto/env:defparameter* env 'cl:*print-base* *print-base*)
    (clef/proto/env:defparameter* env 'cl:*print-radix* *print-radix*)
    (clef/proto/env:defparameter* env 'cl:*print-case* *print-case*)
    (clef/proto/env:defparameter* env 'cl:*print-pretty* *print-pretty*)
    (clef/proto/env:defparameter* env 'cl:*print-gensym* *print-gensym*)
    (clef/proto/env:defparameter* env 'cl:*print-array* *print-array*)
    (clef/proto/env:defparameter* env 'cl:*print-miser-width* *print-miser-width*)
    (clef/proto/env:defparameter* env 'cl:*read-base* *read-base*)
    (clef/proto/env:defparameter* env 'cl:*read-suppress* *read-suppress*)
    (clef/proto/env:defparameter* env 'cl:*read-eval* *read-eval*)
    (clef/proto/env:defparameter* env 'cl:*package* *package*)
    (clef/proto/env:defparameter* env 'cl:*standard-output* *standard-output*)
    (clef/proto/env:defparameter* env 'cl:*standard-input* *standard-input*)
    (clef/proto/env:defparameter* env 'cl:*error-output* *error-output*)
    (clef/proto/env:defparameter* env 'cl:*trace-output* *trace-output*)
    (clef/proto/env:defparameter* env 'cl:*debug-io* *debug-io*)
    (clef/proto/env:defparameter* env 'cl:*query-io* *query-io*)
    (clef/proto/env:defparameter* env 'cl:*terminal-io* *terminal-io*)
    (clef/proto/env:defparameter* env 'cl:*random-state* *random-state*)
    (clef/proto/env:defparameter* env 'cl:*features* *features*)
    (clef/proto/env:defparameter* env 'cl:*gensym-counter* *gensym-counter*)
    (clef/proto/env:defparameter* env 'cl:*read-default-float-format*
      *read-default-float-format*)

    ;;; --- misc ---
    (funcall regh 'cl:error #'error)
    (funcall regh 'cl:cerror #'cerror)
    (funcall regh 'cl:warn #'warn)
    (funcall regh 'cl:signal #'signal)
    (funcall regh 'cl:break #'break)
    (funcall regh 'cl:coerce #'coerce)
    (funcall regh 'cl:proclaim #'proclaim)
    (funcall regh 'cl:sleep #'sleep)
    (funcall regh 'cl:get-internal-real-time #'get-internal-real-time)
    (funcall regh 'cl:get-internal-run-time #'get-internal-run-time)
    (funcall regh 'cl:get-universal-time #'get-universal-time)
    (funcall regh 'cl:get-decoded-time #'get-decoded-time)
    (funcall regh 'cl:encode-universal-time #'encode-universal-time)
    (funcall regh 'cl:decode-universal-time #'decode-universal-time)
    (funcall regh 'cl:internal-time-units-per-second
      cl:internal-time-units-per-second)
    (funcall regh 'cl:room #'room)
    (funcall regh 'cl:ed #'ed)
    (funcall regh 'cl:dribble #'dribble)
    (funcall regh 'cl:apropos #'apropos)
    (funcall regh 'cl:apropos-list #'apropos-list)
    (funcall regh 'cl:describe #'describe)
    (funcall regh 'cl:inspect #'inspect)
    (funcall regh 'cl:documentation #'documentation)
    (funcall regh 'cl:disassemble #'disassemble)
    (funcall regh 'cl:compile #'compile)
    (funcall regh 'cl:compile-file #'compile-file)
    (funcall regh 'cl:compiled-function-p #'compiled-function-p)
    (funcall regh 'cl:constantp #'constantp)
    (funcall regh 'cl:machine-instance #'machine-instance)
    (funcall regh 'cl:machine-type #'machine-type)
    (funcall regh 'cl:machine-version #'machine-version)
    (funcall regh 'cl:software-type #'software-type)
    (funcall regh 'cl:software-version #'software-version)
    (funcall regh 'cl:lisp-implementation-type #'lisp-implementation-type)
    (funcall regh 'cl:lisp-implementation-version #'lisp-implementation-version)
    (funcall regh 'cl:short-site-name #'short-site-name)
    (funcall regh 'cl:long-site-name #'long-site-name)

    ;; constants
    (clef/proto/env:defconstant* env 'cl:t t)
    (clef/proto/env:defconstant* env 'cl:nil nil)
    (clef/proto/env:defconstant* env 'cl:pi pi)
    (clef/proto/env:defconstant* env 'cl:most-positive-fixnum most-positive-fixnum)
    (clef/proto/env:defconstant* env 'cl:most-negative-fixnum most-negative-fixnum)
    (clef/proto/env:defconstant* env 'cl:most-positive-short-float most-positive-short-float)
    (clef/proto/env:defconstant* env 'cl:most-positive-single-float most-positive-single-float)
    (clef/proto/env:defconstant* env 'cl:most-positive-double-float most-positive-double-float)
    (clef/proto/env:defconstant* env 'cl:most-positive-long-float most-positive-long-float)
    (clef/proto/env:defconstant* env 'cl:least-positive-short-float least-positive-short-float)
    (clef/proto/env:defconstant* env 'cl:least-positive-single-float least-positive-single-float)
    (clef/proto/env:defconstant* env 'cl:call-arguments-limit call-arguments-limit)
    (clef/proto/env:defconstant* env 'cl:lambda-parameters-limit lambda-parameters-limit)
    (clef/proto/env:defconstant* env 'cl:multiple-values-limit multiple-values-limit)
    (clef/proto/env:defconstant* env 'cl:array-dimension-limit array-dimension-limit)
    (clef/proto/env:defconstant* env 'cl:array-total-size-limit array-total-size-limit)
    (clef/proto/env:defconstant* env 'cl:array-rank-limit array-rank-limit)
    (clef/proto/env:defconstant* env 'cl:boole-1 boole-1)
    (clef/proto/env:defconstant* env 'cl:boole-2 boole-2)
    (clef/proto/env:defconstant* env 'cl:boole-and boole-and)
    (clef/proto/env:defconstant* env 'cl:boole-andc1 boole-andc1)
    (clef/proto/env:defconstant* env 'cl:boole-andc2 boole-andc2)
    (clef/proto/env:defconstant* env 'cl:boole-c1 boole-c1)
    (clef/proto/env:defconstant* env 'cl:boole-c2 boole-c2)
    (clef/proto/env:defconstant* env 'cl:boole-clr boole-clr)
    (clef/proto/env:defconstant* env 'cl:boole-eqv boole-eqv)
    (clef/proto/env:defconstant* env 'cl:boole-ior boole-ior)
    (clef/proto/env:defconstant* env 'cl:boole-nand boole-nand)
    (clef/proto/env:defconstant* env 'cl:boole-nor boole-nor)
    (clef/proto/env:defconstant* env 'cl:boole-orc1 boole-orc1)
    (clef/proto/env:defconstant* env 'cl:boole-orc2 boole-orc2)
    (clef/proto/env:defconstant* env 'cl:boole-set boole-set)
    (clef/proto/env:defconstant* env 'cl:boole-xor boole-xor)
    (clef/proto/env:defconstant* env 'cl:char-code-limit char-code-limit)
    (clef/proto/env:defconstant* env 'cl:internal-time-units-per-second
      internal-time-units-per-second)

    env))

;;; --- boot-time host glue ---
;;; These % forms are the primitives the boot library builds on. They are
;;; registered as functions/macros that operate on the environment directly.

(defun install-boot-glue (env)
  "Install the % primitives the boot library needs. Names are interned in
CL-USER to match how the boot files are read by the host reader."
  (let* ((cl-user (find-package :cl-user))
         (sym (lambda (name) (intern (string-upcase name) cl-user)))
         (regm (lambda (name fn) (clef/proto/env:bind-macro env (funcall sym name) fn)))
         (regf (lambda (name fn) (clef/proto/env:set-function-value env (funcall sym name) fn))))

    ;;; quasiquote host glue (SBCL comma-struct accessors), in CL-USER.
    (funcall regf "qq-comma-p" (lambda (x) (typep x 'sb-impl::comma)))
    (funcall regf "qq-comma-kind" (lambda (x) (sb-impl::comma-kind x)))
    (funcall regf "qq-comma-expr" (lambda (x) (sb-impl::comma-expr x)))

    ;; %defmacro: (defmacro name expander-fn). The expander-fn is a Lisp
    ;; function of (form env). We wrap it as a macro.
    (funcall regm "%defmacro"
             (lambda (form call-env)
               (declare (ignore call-env))
               (let ((name (resolve-macro-name (cadr form) env))
                     (expander-form (caddr form)))
                 ;; evaluate the expander-fn form to get a function value
                 (let ((expander (primary (clef-eval expander-form env))))
                   (clef/proto/env:bind-macro
                    env name
                    (lambda (f e) (clef-apply expander (list f e)))))
                 `',name)))

    ;; %defun: define a named function in the toplevel.
    (funcall regm "%defun"
             (lambda (form call-env)
               (declare (ignore call-env))
               (let ((name (unquote-name (cadr form)))
                     (fn-form (caddr form)))
                 (let ((fn (primary (clef-eval fn-form env))))
                   (clef/proto/env:set-function-value env name fn))
                 `',name)))

    (funcall regm "%defvar"
             (lambda (form call-env)
               (declare (ignore call-env))
               (destructuring-bind (name init initp) (cdr form)
                 (clef/proto/env:defvar* env (unquote-name name)
                                         (and initp (primary (clef-eval init env))) initp)
                 `',(unquote-name name))))
    (funcall regm "%defparameter"
             (lambda (form call-env)
               (declare (ignore call-env))
               (destructuring-bind (name init) (cdr form)
                 (clef/proto/env:defparameter* env (unquote-name name) (primary (clef-eval init env)))
                 `',(unquote-name name))))
    (funcall regm "%defconstant"
             (lambda (form call-env)
               (declare (ignore call-env))
               (destructuring-bind (name init) (cdr form)
                 (clef/proto/env:defconstant* env (unquote-name name) (primary (clef-eval init env)))
                 `',(unquote-name name))))

    ;; NOTE: %multiple-value-bind, %destructuring-bind, %do, %do*,
    ;; %unwind-protect, %loop, and %setf are SPECIAL OPERATORS, handled
    ;; directly by the evaluator (eval-special in eval.lisp) because they
    ;; compute values rather than returning expansion forms. They are
    ;; intentionally NOT registered as macros here.

    ;; %defstruct
    (funcall regm "%defstruct"
             (lambda (form call-env)
               (declare (ignore call-env))
               (let ((name (unquote-name (cadr form)))
                     (slots (unquote-name (caddr form))))
                 (eval-defstruct env name slots)
                 `',name)))

    ;; %deftype: (name expander-fn-form). Evaluate the expander (a function
    ;; of the type specifier's arguments returning the expansion) and
    ;; register it where typep/subtypep can find it (clos.lisp registry).
    (funcall regm "%deftype"
             (lambda (form call-env)
               (declare (ignore call-env))
               (let ((name (unquote-name (cadr form)))
                     (expander-form (caddr form)))
                 (let ((expander (primary (clef-eval expander-form env))))
                   (register-type-expander env name expander))
                 `',name)))

    env))

(defun eval-do (env vars end fn-form sequential)
  "Implement do/do*. VARS is a list of (var init step). END is (test . results).
FN-FORM evaluates to the body function (a lambda over the vars)."
  (let ((fn (primary (clef-eval fn-form env)))
        (state (mapcar (lambda (v)
                         (cons (car v) (primary (clef-eval (cadr v) env))))
                       vars)))
    (loop
      ;; evaluate end test with current state
      (let ((test-env (clef/proto/env:make-lexical-env env)))
        (dolist (binding state)
          (clef/proto/env:bind-variable test-env (car binding) (cdr binding)))
        (when (primary (clef-eval (car end) test-env))
          ;; evaluate result forms (clef-eval-seq already returns host MV)
          (return (if (cdr end)
                      (clef-eval-seq (cdr end) test-env)
                      (values nil))))
        ;; run body
        (let ((args (mapcar #'cdr state)))
          (clef-apply fn args))
        ;; step
        (let ((new-state
                (if sequential
                    (mapcar (lambda (v)
                              (let ((val (if (cddr v)
                                             (let ((e (clef/proto/env:make-lexical-env env)))
                                               (dolist (b state)
                                                 (clef/proto/env:bind-variable e (car b) (cdr b)))
                                               (primary (clef-eval (caddr v) e)))
                                             (cdr (assoc (car v) state)))))
                                (cons (car v) val)))
                            vars)
                    ;; parallel: compute all steps against current state
                    (let ((e (clef/proto/env:make-lexical-env env)))
                      (dolist (b state)
                        (clef/proto/env:bind-variable e (car b) (cdr b)))
                      (mapcar (lambda (v)
                                (cons (car v)
                                      (if (cddr v)
                                          (primary (clef-eval (caddr v) e))
                                          (cdr (assoc (car v) state)))))
                              vars)))))
          (setf state new-state))))))

(defun set-place (env place value)
  "The setf engine: set PLACE (a quoted place form) to VALUE."
  (cond
    ((symbolp place)
     ;; A symbol place may name a symbol macro (e.g. from with-slots or
     ;; with-accessors); setf of a symbol macro sets the expansion's place.
     (let ((sm (clef/proto/env:lookup-symbol-macro env place)))
       (if sm
           (set-place env (funcall sm place env) value)
           (clef/proto/env:set-variable-value env place value))))
    ((consp place)
     (let ((accessor (car place))
           (args (mapcar (lambda (a) (primary (clef-eval a env))) (cdr place))))
       ;; Prefer a (setf accessor) function when one is bound (CLOS
       ;; :accessor writers); otherwise dispatch to the built-in accessors.
       (let ((setf-name (and (symbolp accessor) (list 'cl:setf accessor))))
         (if (and setf-name (clef/proto/env:function-bound-p env setf-name))
             (clef-apply (clef/proto/env:lookup-function env setf-name)
                         (cons value args))
             (set-accessor-place accessor args value)))))
    (t (error "Cannot setf ~s" place))))

(defun set-accessor-place (accessor args value)
  "Set a place described by ACCESSOR applied to (evaluated) ARGS."
  (case accessor
    ((cl:car) (rplaca (car args) value))
    ((cl:cdr) (rplacd (car args) value))
    ((cl:caar) (rplaca (caar args) value))
    ((cl:cadr) (rplaca (cadr args) value))
    ((cl:cdar) (rplacd (cdar args) value))
    ((cl:cddr) (rplacd (cddr args) value))
    ((cl:caddr) (rplaca (caddr args) value))
    ((cl:nth) (rplaca (nthcdr (car args) (cadr args)) value))
    ((cl:aref) (setf (aref (car args) (cadr args)) value))
    ((cl:svref) (setf (svref (car args) (cadr args)) value))
    ((cl:char) (setf (char (car args) (cadr args)) value))
    ((cl:schar) (setf (schar (car args) (cadr args)) value))
    ((cl:elt) (setf (elt (car args) (cadr args)) value))
    ((cl:gethash) (setf (gethash (car args) (cadr args)) value))
    ((cl:getf) (setf (getf (car args) (cadr args)) value))
    ((cl:symbol-value) (setf (symbol-value (car args)) value))
    ((cl:symbol-plist) (setf (symbol-plist (car args)) value))
    ((cl:fill-pointer) (setf (fill-pointer (car args)) value))
    ((cl:slot-value)
     (if (cinstance-p (car args))
         (setf (clos-slot-value (car args) (cadr args)) value)
         (setf (slot-value (car args) (cadr args)) value)))
    ((cl:subseq) (replace (car args) value :start1 (cadr args) :end1 (caddr args)))
    ((cl:rest) (rplacd (car args) value))
    ((cl:first) (rplaca (car args) value))
    ((cl:second) (rplaca (cdr (car args)) value))
    ((cl:third) (rplaca (cddr (car args)) value))
    (t (error "setf of accessor ~s not supported" accessor)))
  value)

(defun coerce-map-fn (fn)
  "Wrap a Lisp function (clef-function or host function) so host higher-order
functions (mapcar, reduce, sort) can call it."
  (lambda (&rest args) (clef-apply fn args)))

(defun unquote-name (name-form)
  "The % defining macros receive quoted names ((quote sym)) from the boot
file's defmacro-generated expansions. Unwrap to the raw symbol; pass through
anything already a symbol."
  (cond ((and (consp name-form) (eq (car name-form) 'cl:quote)) (cadr name-form))
        ((symbolp name-form) name-form)
        (t name-form)))

(defun resolve-macro-name (name-form env)
  "Resolve a %defmacro name argument to a symbol. Quoted symbols unquote;
a symbol naming a special variable (e.g. *qq-marker*) resolves to its value."
  (let ((n (unquote-name name-form)))
    (if (and (symbolp n)
             (not (keywordp n))
             (clef/proto/env:variable-bound-p env n))
        (clef/proto/env:lookup-variable env n)
        n)))

;;; --- loop (subset) ---

(defun eval-loop (env body)
  "Evaluate a LOOP form. Simple loop (all compound forms) repeats forever;
otherwise the extended-loop engine (loop.lisp) handles the clause vocabulary."
  (if (every #'consp body)
      (loop (clef-eval-seq body env))
      (eval-extended-loop env body)))

;;; The extended-loop engine (eval-extended-loop and helpers) lives in
;;; src/proto/loop.lisp, which supersedes the old for-in-only implementation
;;; that used to be here.

;;; --- defstruct (minimal) ---

(defun eval-defstruct (env name slots)
  "Install a minimal structure backed by a tagged vector."
  (let ((slot-names (mapcar (lambda (s) (if (consp s) (car s) s)) slots))
        (slot-inits (mapcar (lambda (s) (if (and (consp s) (cdr s)) (cadr s) nil)) slots)))
    (let ((ctor-name (intern (format nil "MAKE-~a" (symbol-name name)) (symbol-package name))))
      (clef/proto/env:set-function-value
       env ctor-name
       (lambda (&rest keyargs)
         (let ((v (make-array (1+ (length slot-names)) :initial-element nil)))
           (setf (aref v 0) name)
           (dotimes (i (length slot-names))
             (let* ((init (nth i slot-inits))
                    (kw (intern (symbol-name (nth i slot-names)) :keyword))
                    (val (if (keyword-arg-present kw keyargs)
                             (getf keyargs kw)
                             (eval-struct-init init))))
               (setf (aref v (1+ i)) val)))
           v))))
    (let ((pred-name (intern (format nil "~a-P" (symbol-name name)) (symbol-package name))))
      (clef/proto/env:set-function-value
       env pred-name
       (lambda (x) (and (vectorp x) (> (length x) 0) (eq (aref x 0) name)))))
    (loop for slot in slot-names
          for i from 1
          do (let ((acc-name (intern (format nil "~a-~a" (symbol-name name) (symbol-name slot))
                                     (symbol-package name)))
                   (idx i))
               (clef/proto/env:set-function-value
                env acc-name
                (lambda (obj) (aref obj idx))))))
  name)

(defun eval-struct-init (init)
  (if (or (null init) (keywordp init) (numberp init) (stringp init))
      init
      (primary (clef-eval init (clef/proto/env:make-toplevel-env)))))

(defun keyword-arg-present (kw keyargs)
  (loop for (k v) on keyargs by #'cddr thereis (eq k kw)))

;;; --- boot loader ---

(defvar *boot-files*
  '("src/proto/boot/macros.lisp")
  "Boot library files, evaluated in order into the environment.")

(defun load-boot (env &optional (root *default-pathname-defaults*))
  "Install builtins + boot glue, then evaluate the boot library into ENV."
  (install-builtins env)
  (install-boot-glue env)
  (dolist (rel *boot-files* env)
    (let ((path (merge-pathnames rel root)))
      (load-lisp-file env path))))

(defun load-lisp-file (env path)
  "Read and evaluate each top-level form in PATH in ENV."
  (with-open-file (in path :direction :input)
    (loop for form = (read in nil :eof)
          until (eq form :eof)
          do (clef-eval form env)))
  env)
